# Site settings
title: toc-sync
email: scot.marvin@salesforce.com
description: See where you are in the TOC.
baseurl: "/sync"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    toc_levels: 2..2

# Exclude
exclude: ['node_modules', 'vendor']

theme: jekyll-theme-minimal
